### PR TITLE
Refactor: hate command to use slash commands

### PR DESCRIPTION
**Pull request by shawnyu5**
The command `hate` has been refactored to use slash commands. However I was not able to get `imgFlip` working so I was not able to fully test out the command, but the slash command behavior behaves the same way as the regular text command.

Should wait for #21 to be merged to clean up commit history.

### CODE REVIEW

**Comment by 416rehman** [comment]
The logic is reused in both the method and results in code duplication. Move the logic to a seperate function and call it from both the methods. Use the `avatar` command as a reference https://github.com/416rehman/splite/blob/production/src/commands/info/avatar.js

**Comment by shawnyu5** [comment]
Right okay fixed

**Comment by shawnyu5** [comment]
Also added nodemon as a dev dependency

**Comment by shawnyu5** [comment]
Should I be working that hard to keep compatibility with older text commands?

**Review by 416rehman — APPROVED** [review]
looks good

**Pull request merged**
